//! Pure task-list state machine for Pi.
use serde::{Deserialize, Serialize};
use std::fmt::Write as _;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "state")]
pub enum TodoStatus { Open, InProgress, Done, Dropped, Blocked { reason: String } }
impl TodoStatus { pub const fn is_terminal(&self)->bool { matches!(self,Self::Done|Self::Dropped) } pub const fn label(&self)->&'static str { match self {Self::Open=>"open",Self::InProgress=>"in_progress",Self::Done=>"done",Self::Dropped=>"dropped",Self::Blocked{..}=>"blocked"} } }
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)] pub struct TodoTask { pub content:String, #[serde(flatten)] pub status:TodoStatus }
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)] pub struct TodoPhase { #[serde(skip_serializing_if="Option::is_none")] pub name:Option<String>, pub tasks:Vec<TodoTask> }
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)] pub struct TodoList { pub phases:Vec<TodoPhase> }
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)] pub enum TodoError { #[error("{0}")] Validation(String) }
fn err(s:impl Into<String>)->TodoError { TodoError::Validation(s.into()) }
impl TodoList {
 pub fn is_empty(&self)->bool { self.phases.iter().all(|p|p.tasks.is_empty()) }
 fn tasks(&self)->impl Iterator<Item=&TodoTask>{self.phases.iter().flat_map(|p|&p.tasks)}
 fn tasks_mut(&mut self)->impl Iterator<Item=&mut TodoTask>{self.phases.iter_mut().flat_map(|p|&mut p.tasks)}
 fn find_mut(&mut self,c:&str)->Result<&mut TodoTask,TodoError>{self.tasks_mut().find(|t|t.content==c).ok_or_else(||err(format!("unknown task {c:?}; tasks are addressed by their exact content")))}
 pub fn current(&self)->Option<&TodoTask>{self.tasks().find(|t|matches!(t.status,TodoStatus::InProgress))}
 pub fn progress(&self)->(usize,usize){self.tasks().fold((0,0),|(s,n),t|(s+usize::from(t.status.is_terminal()),n+1))}
 pub fn auto_promote(&mut self){if self.current().is_none()&&let Some(t)=self.tasks_mut().find(|t|matches!(t.status,TodoStatus::Open)){t.status=TodoStatus::InProgress}}
 pub fn summary_line(&self)->Option<String>{if self.is_empty(){None}else{let(s,n)=self.progress();Some(format!("{s}/{n} · {}",self.current().map_or("(no task in progress)",|t|t.content.as_str())))}}
 pub fn render(&self)->String{if self.is_empty(){return "(todo list is empty)".into()}let mut o=String::new();for(i,p)in self.phases.iter().enumerate(){if let Some(n)=&p.name{let _=writeln!(o,"## {n}")}else if self.phases.len()>1{let _=writeln!(o,"## phase {}",i+1)}for t in &p.tasks{match &t.status{TodoStatus::Blocked{reason}=>{let _=writeln!(o,"[!] ({reason}) {}",t.content)},s=>{let m=match s{TodoStatus::Open=>"[ ]",TodoStatus::InProgress=>"[>]",TodoStatus::Done=>"[x]",TodoStatus::Dropped=>"[-]",_=>unreachable!()};let _=writeln!(o,"{m} {}",t.content)}}} }let(s,n)=self.progress();let _=write!(o,"\n{s}/{n} settled");o}
}
#[derive(Debug,Clone,Deserialize)]
#[serde(rename_all="snake_case",tag="op")]
pub enum TodoOp { Init{#[serde(default)] phases:Option<Vec<TodoInitPhase>>,#[serde(default)] tasks:Option<Vec<String>>}, Start{task:String}, Done{task:String}, Drop{task:String}, Block{task:String,reason:String}, Unblock{task:String}, Rm{task:String}, Append{#[serde(default)] phase:Option<String>,tasks:Vec<String>}, View }
#[derive(Debug,Clone,Deserialize)] pub struct TodoInitPhase { #[serde(default)] pub name:Option<String>, pub tasks:Vec<String> }
fn non_empty(ts:&[String],op:&str)->Result<(),TodoError>{if ts.is_empty(){return Err(err(format!("{op} requires at least one task")))}if ts.iter().any(|t|t.trim().is_empty()){return Err(err(format!("{op} tasks must not be blank")))}Ok(())}
pub fn apply_op(l:&mut TodoList,op:&TodoOp)->Result<bool,TodoError>{match op{TodoOp::Init{phases,tasks}=>{let n=match(phases,tasks){(Some(ps),None)=>{if ps.is_empty(){return Err(err("init requires at least one phase"))}for p in ps{non_empty(&p.tasks,"init")}?TodoList{phases:ps.iter().map(|p|TodoPhase{name:p.name.clone(),tasks:p.tasks.iter().map(|c|TodoTask{content:c.clone(),status:TodoStatus::Open}).collect()}).collect()}},(None,Some(ts))=>{non_empty(ts,"init")?TodoList{phases:vec![TodoPhase{name:None,tasks:ts.iter().map(|c|TodoTask{content:c.clone(),status:TodoStatus::Open}).collect()}]}},_=>(return Err(err("init requires exactly one of `phases` or `tasks`")))};*l=n;l.auto_promote();Ok(true)},TodoOp::Start{task}=>{if l.find_mut(task)?.status.is_terminal(){return Err(err("completed tasks never revert"))}for t in l.tasks_mut(){if matches!(t.status,TodoStatus::InProgress){t.status=TodoStatus::Open}}l.find_mut(task)?.status=TodoStatus::InProgress;Ok(true)},TodoOp::Done{task}=>{let t=l.find_mut(task)?;if matches!(t.status,TodoStatus::Dropped){return Err(err("dropped tasks never revert"))}t.status=TodoStatus::Done;l.auto_promote();Ok(true)},TodoOp::Drop{task}=>{let t=l.find_mut(task)?;if matches!(t.status,TodoStatus::Done){return Err(err("done tasks never revert"))}t.status=TodoStatus::Dropped;l.auto_promote();Ok(true)},TodoOp::Block{task,reason}=>{if reason.trim().is_empty(){return Err(err("block requires a non-empty reason"))}let t=l.find_mut(task)?;if t.status.is_terminal(){return Err(err("completed tasks never revert"))}t.status=TodoStatus::Blocked{reason:reason.clone()};l.auto_promote();Ok(true)},TodoOp::Unblock{task}=>{let t=l.find_mut(task)?;if !matches!(t.status,TodoStatus::Blocked{..}){return Err(err("task is not blocked"))}t.status=TodoStatus::Open;l.auto_promote();Ok(true)},TodoOp::Rm{task}=>{let _=l.find_mut(task)?;for p in &mut l.phases{p.tasks.retain(|t|t.content!=*task)}l.auto_promote();Ok(true)},TodoOp::Append{phase,tasks}=>{non_empty(tasks,"append")?;let n=tasks.iter().map(|c|TodoTask{content:c.clone(),status:TodoStatus::Open});if let Some(name)=phase{if let Some(p)=l.phases.iter_mut().find(|p|p.name.as_deref()==Some(name)){p.tasks.extend(n)}else{l.phases.push(TodoPhase{name:Some(name.clone()),tasks:n.collect()})}}else if let Some(p)=l.phases.last_mut(){p.tasks.extend(n)}else{l.phases.push(TodoPhase{name:None,tasks:n.collect()})}l.auto_promote();Ok(true)},TodoOp::View=>Ok(false)}}
#[cfg(test)]mod tests{use super::*;#[test]fn state_machine_promotes(){let mut l=TodoList::default();apply_op(&mut l,&TodoOp::Init{phases:None,tasks:Some(vec!["a".into(),"b".into()])}).unwrap();assert_eq!(l.current().unwrap().content,"a");apply_op(&mut l,&TodoOp::Done{task:"a".into()}).unwrap();assert_eq!(l.current().unwrap().content,"b");}}
